language: node_js

os:
  - linux
  - osx

branches:
  only:
    - master

node_js:
  - "node"
  - "6"
  - "5"
  - "4"

before_script:
 - chmod +x ./scripts/travis-build.sh

script: ./scripts/travis-build.sh
